spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/daelim_hackathon
    username: root
    password: wnstjd99!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: true

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

# aws
cloud:
  aws:
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

    # s3
    s3:
      bucket: ai.file.storage.bucket

    # ami
    credentials:
      access-key: AKIA4R3BUPFXTDBHUUSV
      secret-key: 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

# secret key
SECRET_KEY: dFBriSjSMoRusTLjAmQP9lHV64VMYhn0gdwGaX2h0tROQ2ipJL

# naver credentials
NAVER:
  clientId: cnvt27cb6z
  clientSecret: 6drfEupGy3WFJCJRgN5SnZeZgyETBdEAvKk3Ybm4